name: build ios

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest
    - run: brew install tree
    - name: Download Pre Compiled Dependencies
      run: cd shell && ./download-pre.sh ijk ios
    - run: pod lib lint --allow-warnings --platforms=ios
